name: Quartz
version: @version@
description:
authors: [viveleroi]
website:
api-version: @apiversion@
main: network.darkhelmet.quartz.Quartz
depend: [PlaceholderAPI]
commands:
  events:
    description: Lists events
    usage: /events
  quartz:
    description: Manage events
    usage: /quartz